---
# tasks file for ansible-role-snmpd/

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install required packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  when: item|string not in ansible_facts.packages
  with_items: snmp_packages

- name: "net-snmp-devel package, if missing"
  ansible.builtin.package:
    name: "net-snmp-devel"
    state: present
  when:
    - "'net-snmp-devel' not in ansible_facts.packages"
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version <= '6'
  
