---
# handlers file for ansible-role-snmpd/
- name: "Stop SNMP daemon"
  ansible.builtin.service:
    name: "{{ snmp_daemon }}"
    state: stopped

- name: "Start SNMP daemon"
  ansible.builtin.service:
    name: "{{ snmp_daemon }}"
    state: started